onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /PROCESSING_UNIT_tb/i_CLK
add wave -noupdate /PROCESSING_UNIT_tb/i_RST_N
add wave -noupdate /PROCESSING_UNIT_tb/i_CLK_EN
add wave -noupdate /PROCESSING_UNIT_tb/o_Y_done
add wave -noupdate /PROCESSING_UNIT_tb/rdEnb
add wave -noupdate /PROCESSING_UNIT_tb/o_Y_done_enb
add wave -noupdate /PROCESSING_UNIT_tb/o_Y_addr
add wave -noupdate /PROCESSING_UNIT_tb/o_Y_active
add wave -noupdate /PROCESSING_UNIT_tb/Data_Type_Conversion_out1_addr
add wave -noupdate /PROCESSING_UNIT_tb/Data_Type_Conversion7_out1_addr_delay_1
add wave -noupdate /PROCESSING_UNIT_tb/tb_enb_delay
add wave -noupdate /PROCESSING_UNIT_tb/fp_i_X3
add wave -noupdate /PROCESSING_UNIT_tb/rawData_i_X3
add wave -noupdate /PROCESSING_UNIT_tb/status_i_X3
add wave -noupdate /PROCESSING_UNIT_tb/holdData_i_X3
add wave -noupdate /PROCESSING_UNIT_tb/i_X3_offset
add wave -noupdate /PROCESSING_UNIT_tb/i_X3
add wave -noupdate /PROCESSING_UNIT_tb/Data_Type_Conversion6_out1_addr_delay_1
add wave -noupdate /PROCESSING_UNIT_tb/fp_i_X2
add wave -noupdate /PROCESSING_UNIT_tb/rawData_i_X2
add wave -noupdate /PROCESSING_UNIT_tb/status_i_X2
add wave -noupdate /PROCESSING_UNIT_tb/holdData_i_X2
add wave -noupdate /PROCESSING_UNIT_tb/i_X2_offset
add wave -noupdate /PROCESSING_UNIT_tb/i_X2
add wave -noupdate /PROCESSING_UNIT_tb/Data_Type_Conversion5_out1_addr_delay_1
add wave -noupdate /PROCESSING_UNIT_tb/fp_i_X1
add wave -noupdate /PROCESSING_UNIT_tb/rawData_i_X1
add wave -noupdate /PROCESSING_UNIT_tb/status_i_X1
add wave -noupdate /PROCESSING_UNIT_tb/holdData_i_X1
add wave -noupdate /PROCESSING_UNIT_tb/i_X1_offset
add wave -noupdate /PROCESSING_UNIT_tb/i_X1
add wave -noupdate /PROCESSING_UNIT_tb/Data_Type_Conversion4_out1_addr_delay_1
add wave -noupdate /PROCESSING_UNIT_tb/fp_i_X0
add wave -noupdate /PROCESSING_UNIT_tb/rawData_i_X0
add wave -noupdate /PROCESSING_UNIT_tb/status_i_X0
add wave -noupdate /PROCESSING_UNIT_tb/holdData_i_X0
add wave -noupdate /PROCESSING_UNIT_tb/i_X0_offset
add wave -noupdate /PROCESSING_UNIT_tb/i_X0
add wave -noupdate /PROCESSING_UNIT_tb/Data_Type_Conversion3_out1_addr_delay_1
add wave -noupdate /PROCESSING_UNIT_tb/fp_i_W3
add wave -noupdate /PROCESSING_UNIT_tb/rawData_i_W3
add wave -noupdate /PROCESSING_UNIT_tb/status_i_W3
add wave -noupdate /PROCESSING_UNIT_tb/holdData_i_W3
add wave -noupdate /PROCESSING_UNIT_tb/i_W3_offset
add wave -noupdate /PROCESSING_UNIT_tb/i_W3
add wave -noupdate /PROCESSING_UNIT_tb/Data_Type_Conversion2_out1_addr_delay_1
add wave -noupdate /PROCESSING_UNIT_tb/fp_i_W2
add wave -noupdate /PROCESSING_UNIT_tb/rawData_i_W2
add wave -noupdate /PROCESSING_UNIT_tb/status_i_W2
add wave -noupdate /PROCESSING_UNIT_tb/holdData_i_W2
add wave -noupdate /PROCESSING_UNIT_tb/i_W2_offset
add wave -noupdate /PROCESSING_UNIT_tb/i_W2
add wave -noupdate /PROCESSING_UNIT_tb/Data_Type_Conversion1_out1_addr_delay_1
add wave -noupdate /PROCESSING_UNIT_tb/fp_i_W1
add wave -noupdate /PROCESSING_UNIT_tb/rawData_i_W1
add wave -noupdate /PROCESSING_UNIT_tb/status_i_W1
add wave -noupdate /PROCESSING_UNIT_tb/holdData_i_W1
add wave -noupdate /PROCESSING_UNIT_tb/i_W1_offset
add wave -noupdate /PROCESSING_UNIT_tb/i_W1
add wave -noupdate /PROCESSING_UNIT_tb/Data_Type_Conversion_out1_active
add wave -noupdate /PROCESSING_UNIT_tb/Data_Type_Conversion_out1_enb
add wave -noupdate /PROCESSING_UNIT_tb/Data_Type_Conversion_out1_addr_delay_1
add wave -noupdate /PROCESSING_UNIT_tb/fp_i_W0
add wave -noupdate /PROCESSING_UNIT_tb/rawData_i_W0
add wave -noupdate /PROCESSING_UNIT_tb/status_i_W0
add wave -noupdate /PROCESSING_UNIT_tb/holdData_i_W0
add wave -noupdate /PROCESSING_UNIT_tb/i_W0_offset
add wave -noupdate /PROCESSING_UNIT_tb/i_W0
add wave -noupdate /PROCESSING_UNIT_tb/check1_done
add wave -noupdate /PROCESSING_UNIT_tb/snkDonen
add wave -noupdate /PROCESSING_UNIT_tb/tb_enb
add wave -noupdate /PROCESSING_UNIT_tb/ce_out
add wave -noupdate /PROCESSING_UNIT_tb/o_Y
add wave -noupdate /PROCESSING_UNIT_tb/o_Y_enb
add wave -noupdate /PROCESSING_UNIT_tb/o_Y_lastAddr
add wave -noupdate /PROCESSING_UNIT_tb/o_Y_addr_delay_1
add wave -noupdate /PROCESSING_UNIT_tb/fp_o_Y_expected
add wave -noupdate /PROCESSING_UNIT_tb/o_Y_expected
add wave -noupdate /PROCESSING_UNIT_tb/status_o_Y_expected
add wave -noupdate /PROCESSING_UNIT_tb/o_Y_ref
add wave -noupdate /PROCESSING_UNIT_tb/o_Y_testFailure
add wave -noupdate /PROCESSING_UNIT_tb/testFailure
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {1 ns}
